# Generated by Django 4.2.11 on 2024-04-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_inventory_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
