# Generated by Django 4.2.11 on 2024-04-02 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_sex_alter_patient_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
