# Generated by Django 4.2.11 on 2024-04-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_prescription_is_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.IntegerField(),
        ),
    ]
